### PR TITLE
CTECH-2282: Added initial example py file for async requests

### PR DESCRIPTION
**Pull request by adamMQM**
# Pull Request Checklist

- [x] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [x] Tests pass

# Description of the PR

Added an example to show how to use async_req in lusid-sdk

### CODE REVIEW

**Comment by rizwansaeed** [comment]
Can they be converted to run as tests so they run in the pipelines?

**Comment by adamMQM** [comment]
Screenshot 2022-11-17 at 17 37 39

**Comment by rizwansaeed** [comment]
would it be easy to change the `print` to use `logger`?

**Review by rizwansaeed — APPROVED** [review]

**Pull request merged**
